inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rails.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.6

Layout/IndentationConsistency:
  EnforcedStyle: normal

Layout/DotPosition:
  EnforcedStyle: leading

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Style/FrozenStringLiteralComment:
  Enabled: true
