default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: readme-translation_development
  host: localhost
  username: root
  password:

test:
  <<: *default
  database: readme-translation_test
  host: localhost
  username: root
  password:

production:
  <<: *default
  url: "<%= Rails.application.credentials.cleardb_database_url %>"

